# This is a basic workflow to help you get started with Actions

name: Run Tox

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types: [ synchronize ]
  pull_request_target:
    branches: 
    - main
    types: [ synchronize ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Runs a set of commands using the runners shell
      - name: Install Tox and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
          pip install tox

      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
